[[topnav]]
  identifier = "quickstart"
  name = "quickstart"
  url = "/quickstart"
  weight = 1

[[topnav]]
  identifier = "docs"
  name = "docs"
  url = "/docs/development_quickstart"
  weight = 2

[[topnav]]
  identifier = "blog"
  name = "blog"
  url = "/blog"
  weight = 3

[[topnav]]
  identifier = "faq"
  name = "faq"
  url = "/faq"
  weight = 4

[[topnav]]
  identifier = "community"
  name = "community"
  url = "/community"
  weight = 5

[[sidenav]]
    name = "Develop a connector"
    weight = 4
    parent = "Developer Docs"

[[sidebar]]
    name = "faq"
    weight = -120
    identifier = "faq"
    url = "/faq/"

[[sidenav]]
    name = "Blog"
    weight = -130
    identifier = "blog"
    url = "/blog/"


