baseURL = "https://syndesis.io/"
languageCode = "en-gb"
enableGitInfo = true
title = "syndesis"
theme = "syndesis"
canonifyURLs = true
googleAnalytics = "UA-98663114-1"

[[menu.topnav]]
    name = "code"
    weight = -110
    identifier = "code"
    url = "https://github.com/syndesisio"

[[menu.sidenav]]
    name = "About Syndesis"
    pre = "<i class='fa fa-fw fa-download'></i>"
    url = "/about/"
    weight = -200
[[menu.sidenav]]
    name = "Getting Started"
    pre = "<i class='fa fa-cubes'></i>"
    url = "/getting-started/"
    weight = -180
[[menu.sidenav]]
    name = "User Guide"
    identifier = "users"
    pre = "<i class='fa fa-fw fa-puzzle-piece'></i>"
    url = "/users/"
    weight = -170
[[menu.sidenav]]
    name = "Developer Guide"
    identifier = "developers"
    pre = "<i class='fa fa-fw fa-road'></i>"
    weight = -100
[[menu.sidenav]]
    name = "Community"
    identifier = "community"
    pre = "<i class='fa fa-fw fa-file-text'></i>"
    weight = -90
[[menu.sidenav]]
    name = "Testing"
    identifier = "testing"
    pre = "<i class='fa fa-fw fa-desktop'></i>"
    weight = -85
[[menu.sidenav]]
    name = "FAQ"
    url = "/faq/"
    pre = "<i class='fa fa-fw fa-file-text'></i>"
    weight = -170
[[menu.sidenav]]
    name = "Models"
    identifier = "models"
    pre = "<i class='fa fa-fw fa-tags'></i>"
    weight = -70
[[menu.sidenav]]
    parent = "community"
    name = "Contact Us"
    url = "/contact/"
    weight = 150
[[menu.sidenav]]
	parent = "developers"
    name = "Architecture"
    pre = "<i class='fa fa-fw fa-book'></i>"
    weight = -40
[[menu.sidenav]]
    name = "Troubleshooting"
    identifier = "troubleshooting"
    pre = "<i class='fa fa-fw fa-wrench'></i>"
    weight = -30
[[menu.sidenav]]
	parent = "models"
    name = "Connections"
    url = "/connections/"
    pre = "<i class='fa fa-fw fa-cogs'></i>"
    weight = -25
[[menu.sidenav]]
	parent = "models"
    name = "Templates"
    url = "/templates/"
    pre = "<i class='fa fa-fw fa-cogs'></i>"
    weight = -26
[[menu.sidenav]]
    name = "API Docs"
    pre = "<i class='fa fa-fw fa-space-shuttle'></i>"
    weight = -20
    url = "/api-docs/"
