baseURL: "/"
languageCode: "en-gb"
title: "Syndesis - Open source integration platform"
theme: "syndesis"
canonifyURLs: true
googleAnalytics: "UA-98663114-1"
metaDataFormat: "yaml"
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsStyle: github
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: true
    highlight:
      codeFences: true
      lineNos: true
      lineNumbersInTable: true
      noClasses: false
    tableOfContents:
      endLevel: 4
      ordered: false
      startLevel: 2

outputs:
  home: ["HTML", "RSS"]

outputFormats:
  outputFormats.SearchIndex:
    mediaType: "application/json"
    baseName: "index"
    isPlainText: true
    notAlternative: true
