version: 2
jobs:
  build:
    docker:
      - image: node:7.10-alpine

    working_directory: /workspace

    steps:
      - run:
          name: Install tools 
          command: |-
            apk update -q && apk upgrade && apk add -q --no-progress git curl openssh-client tar
            curl -fsSL https://github.com/spf13/hugo/releases/download/v0.20.7/hugo_0.20.7_Linux-64bit.tar.gz | tar xz -C /usr/local/bin hugo
            yarn global add gulp-cli

      - checkout

      - restore_cache:
          keys:
            - node-modules-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: |-
            yarn
            npm rebuild node-sass

      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      
      - run:
          name: Build site
          command: gulp build

      - add_ssh_keys:
          fingerprints:
            - "4b:0a:a7:14:3f:99:69:8c:fa:36:d0:92:28:c4:05:79"

      - deploy:
          command: |
            if [[ "${CIRCLE_PROJECT_USERNAME}" =~ ^(jimmidyson\|syndesisio)$ && "${CIRCLE_BRANCH}" == "master" ]]; then
              git config --global user.email "${GIT_EMAIL}"
              git config --global user.name "${GIT_NAME}"

              ./publish-to-gh-pages.sh
            fi
